# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kostiscodefresh/helm-promotion-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80


## Application level settings  
appMode: qa
certificatePath: /etc/ssl/qa
paypalURLLocation: https://qa.paypal.example.com
databaseUser: qa-user
databasePassword: qa-password




